(define (problem usu_quad_prob02)
(:domain usu-main-quad)
(:objects OLDMAIN ANIMALSCIENCES RAYBWEST AGRICULTURALSCIENCES MiddleOfQuad EAST NORTH SOUTH WEST Agent01)
(:init
(building OLDMAIN) (building ANIMALSCIENCES) (building RAYBWEST) (building AGRICULTURALSCIENCES) 
(place MiddleOfQuad)  (direction EAST) (direction NORTH) (direction SOUTH) (direction WEST) 
(agent Agent01) (at Agent01 RAYBWEST) (facing Agent01 NORTH)
(path OLDMAIN MiddleOfQuad EAST)
(path MiddleOfQuad OLDMAIN WEST)
(path MiddleOfQuad ANIMALSCIENCES NORTH)
(path ANIMALSCIENCES MiddleOfQuad SOUTH)
(path RAYBWEST MiddleOfQuad NORTH)
(path MiddleOfQuad RAYBWEST SOUTH)
(path MiddleOfQuad AGRICULTURALSCIENCES EAST)
(path AGRICULTURALSCIENCES MiddleOfQuad WEST))
(:goal (and (at Agent01 AGRICULTURALSCIENCES) (facing Agent01 EAST))))