(define (problem usu_quad_prob01)
(:domain usu-main-quad)
(:objects OLDMAIN ANIMALSCIENCES RAYBWEST AGRICULTURALSCIENCES MiddleOfQuad EAST NORTH SOUTH WEST Agent01)
(:init
(building OLDMAIN) (building ANIMALSCIENCES) (building RAYBWEST) (building AGRICULTURALSCIENCES) 
(place MiddleOfQuad)  (direction EAST) (direction NORTH) (direction SOUTH) (direction WEST) 
(agent Agent01) (at Agent01 OLDMAIN) (facing Agent01 EAST)
(path OLDMAIN MiddleOfQuad EAST)
(path MiddleOfQuad OLDMAIN WEST)
(path MiddleOfQuad ANIMALSCIENCES NORTH)
(path ANIMALSCIENCES MiddleOfQuad SOUTH)
(path RAYBWEST MiddleOfQuad NORTH)
(path MiddleOfQuad RAYBWEST SOUTH)
(path MiddleOfQuad AGRICULTURALSCIENCES EAST)
(path AGRICULTURALSCIENCES MiddleOfQuad WEST))
(:goal (and (at Agent01 ANIMALSCIENCES) (facing Agent01 NORTH))))